name: Update Files

on:
  pull_request:
    branches: [ main ]

permissions: {}

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    outputs:
      changes_detected: ${{ steps.auto-commit.outputs.changes_detected }}
    permissions:
      contents: write # to push readme changes
      pull-requests: write # to comment on PRs
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Generate Bot Token
        id: generate_token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ secrets.ACTIONS_MAINTENANCE_APP_ID }}
          private-key: ${{ secrets.ACTIONS_MAINTENANCE_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup Base Environment
        uses: ./.github/actions/setup-base-environment

      - name: Generate Readme
        run: ./gradlew generateReadme

      - name: Commit and Push if changed
        id: auto-commit
        uses: TimSchoenle/actions/actions/common/commit-changes@8f15b94f827ea2005c0e32cadc86bb50969633dd # actions-common-commit-changes-v1.1.4
        with:
          commit_message: 'docs: auto-update documentation'
          file_pattern: 'README.md'
          token: ${{ steps.generate_token.outputs.token }}

      - name: Comment on PR
        if: steps.auto-commit.outputs.changes_detected == 'true' && github.event_name == 'pull_request'
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'üìù `README.md` have been auto-updated with the latest details.'
            })

  auto-format:
    name: Auto-Format
    needs: update-readme
    if: needs.update-readme.outputs.changes_detected == 'false'
    uses: TimSchoenle/actions/.github/workflows/java-gradle-auto-spotless.yaml@43d918ab4de8b15844c8f5313718ee7050340a68 # workflows-java-gradle-auto-spotless-v1.0.2
    with:
      java_version: '25'
    secrets:
      bot_app_id: ${{ secrets.ACTIONS_MAINTENANCE_APP_ID }}
      bot_private_key: ${{ secrets.ACTIONS_MAINTENANCE_PRIVATE_KEY }}
